export const ActionTypes = {
  ALL_PRODUCTS: "ALL_PRODUCTS",
  LOAD_MORE: "LOAD_MORE",
  LOAD_MORE_SUCCESS: "LOAD_MORE_SUCCESS",
  FETCH_DATA: "FETCH_DATA",
  GET_PRODUCT: "GET_PRODUCT",
  FETCH_ERROR: "FETCH_ERROR",
};
